eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
        instance: http://localhost:8761/eureka/
  instance:
    hostname: localhost
welcome:
  message: WelCome to this App
